site_name: Qudit Cliffords
# site_url: https://test.org

plugins:
- search
- autorefs
- mkdocstrings:
    handlers:
      python:
        options:
            relative_crossrefs: true    
            docstring_section_style: spacy
          


nav:
  - Home: index.md
  - Usage: usage.md
  - API Reference:
    - Clifford Gates: clifford.md
    - Symplectic Matrices: symplectic.md
    - D-Nary Matrices: dnary.md




theme:
  name: "readthedocs"



