site_name: Qudit Cliffords
# site_url: https://test.org



nav:
  - Home: index.md
  - Usage: usage.md
  - API Reference:
    - Clifford Gates: clifford.md
    - Symplectic Matrices: symplectic.md
    - DNary Matrices: dnary.md


plugins:
- search
- autorefs
- mkdocstrings:
    handlers:
      python:
        paths: []
      
theme:
  name: "readthedocs"


